### PR TITLE
Add(draw): draw points as icons

### PR DESCRIPTION
**Pull request by drekss**
Possibility to add icons url in the app config to make an icon list in the drawing tool.

In the drawing tool you can choose an icon in a list and draw point that will represent your the icon.

There is also the possibility to make your icon list from a mobile device folder. It works with Ionic cordova.

### CODE REVIEW

**Comment by mbarbeau** [comment]
Hi Déreck,

- There is an error when there are no icons defined:
ERROR Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.

- Can you fix the CSS for color-pickers ? The color-picker exceeds the frame and there is too much space between the 2 form-fields.

- The tool documentation should also be added for the configuration of the icons.

Thanks !

**Comment by drekss** [comment]
> Hi Déreck,
> 
> * There is an error when there are no icons defined:
>   ERROR Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.
> * Can you fix the CSS for color-pickers ? The color-picker exceeds the frame and there is too much space between the 2 form-fields.
> * The tool documentation should also be added for the configuration of the icons.
> 
> Thanks !

Hi,

It has been fixed! You can test it and comeback with more comments about the feature.

**Comment by mbarbeau** [comment]
It was wanted to close this PR?

**Review by mbarbeau — CHANGES_REQUESTED** [review]
Thanks for the changes. I have some other small changes

1) Add the choice, "no icon" to cancel the icon selection and use the style instead.
2) The labels are on the icons, possible to put an offset?
3) Change the name of the config to drawingTool.icons

Ideally, we should be able to choose a different icon for each point. This can be done at the same time as selecting a different style for each entity.

**Pull request closed without merging**
