### PR TITLE
fix-feat(*context) now can unset favorite and new Icon style 

### PR DESCRIPTION
**Pull request by josee666**
**What is the current behavior?** (You can also link to an open issue here)
   - unabled to unset fav context
   - icone style black and large
  https://github.com/infra-geo-ouverte/igo2/issues/811

**What is the new behavior?**
- unset fav with another click on icon
- new param for light style on fav icon

**Does this PR introduce a breaking change?** (check one with "x")
- [ X] Yes
- [ ] No

The param in config file has been place in new object contextConfig.favoriteContext ***
for nonAuth who use favorite, you have to change the param in config file. 
If you don't, no problem on app, but you will lost the favorite button if there was true.
Else no problem

before :
 "favoriteContext4NonAuthenticated": true,

after:
      "contextConfig" : {
               "favoriteContext": {
                    "favoriteContext4NonAuthenticated": true,
                    "lightIcon": false
                }
            }

**Other information**:
@pel, @PhilippeLafreniere18 this need to be tests with Authenficated just to be sure no impact on that use case.

First try was "context" isteed of "contextConfig" for the first object name but that cause bad side effect, default fav and  color. Maybe interfert with apiContext config... so i put contextConfig for name.

### CODE REVIEW

**Review by pelord — CHANGES_REQUESTED** [review]
move the config within context config...
https://github.com/infra-geo-ouverte/igo2/blob/next/docs/config_json.rst#L360

**Comment by josee666** [comment]
change for config arrangement done

**Review by PhilippeLafreniere18 — CHANGES_REQUESTED** [review]

**Review by PhilippeLafreniere18 — CHANGES_REQUESTED** [review]
Would be great also to have a message that tells you that the default context has now been set favorite (as you "unfavorite" the current one)

**Comment by pelord** [comment]
@ameliebernier @josee666 waiting for requested changes

**Pull request closed without merging**
