### PR TITLE
Display distances of the measures of a polygon 

### PR DESCRIPTION
**Pull request by almat65**
**Please check if the PR fulfills these requirements**
- [ x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
area is displayed once the polygon is finished. 

**What is the new behavior?**
area and distances are displayed once the polygon is finished. the option for display only areas or areas with distances present.
the tooltips of distances are kept when you switch between the differents sections. The properties of the tooltips-display are saved when you turn-off a layer. 

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

### CODE REVIEW

**Comment by mbarbeau** [comment]
Suggestion:
Instead of having "Measure on map" which is distance for lines and area for polygons, I think it would be better to have "Show distances" and "Show areas".

**Review by mbarbeau — CHANGES_REQUESTED** [review]

**Comment by almat65** [comment]
_Suggestion:
Instead of having "Measure on map" which is distance for lines and area for polygons, I think it would be better to have "Show distances" and "Show areas"._

quand on a des polygones sur la carte et on est dans l'onglet "distances", on voit "afficher les distances". et si on ferme ce toggle, on cache les superficies aussi. Et la même situation quand on clique sur toggle "afficher les superficies" - il cache les distances. je lèserais "afficher les mesures" comme ça a été avant. 
image

**Comment by mbarbeau** [comment]
Ce que je veux dire c'est que actuellement "afficher les mesures" contrôlent à la fois distance et superficie et qu'on a ajouté un "Afficher les distances pour les superficies" donc c'est un peu mêlant. Pour afficher les distances, selon dans quel onglet que tu es, ce n'est pas le même toggle. Je crois que uniformiser les toggles dans les 2 onglets seraient mieux.

Dans l'onglet Distance:
- "Afficher les distances" affichera les distance sur les lignes

Dans l'onglet Superficie:
- "Afficher les distances" affichera les distance sur les polygones
- "Afficher les superficies" affichera la superficie des polygones

**Comment by pelord** [comment]
Ready to be merge

**Pull request merged**
