### PR TITLE
feat(feature): possibility to generate mvt data source as regular features or as renderFeatures.

### PR DESCRIPTION
**Pull request by drekss**
feat(feature): possibility to generate mvt data source as regular features or as renderFeatures.

renderFeature is optimized for rendering and hit detection.

### CODE REVIEW

**Comment by drekss** [comment]
{
      "title": "tenure-elcano-server",
      "declutter": true,
      "visible": false,
      "opacity" : 0.5,
      "styleByAttribute": {
        "type": "regular",
        "attribute": "TYPE",
        "data": [ "Priv"],
        "fill": ["red"],
        "stroke": ["rgba(255,255,0,0)"],
        "width" : [5],
        "label": "TYPE",
        "baseStyle": {
        "stroke": {
          "color": "rgba(255,255,0,0)"
        },
        "fill": {
          "color": "rgba(255,255,0,0)"
        }
      }},
      "sourceOptions": {
        "queryable": true,
        "url": "http://elcano:8080/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=TuilageSmartFaune:Tenures&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/x-protobuf;type=mapbox-vector&TILECOL={x}&TILEROW={y}",
        "pathOffline": "https://io.ion.igo2/_app_file_/storage/emulated/0/Android/data/io.ionic.igo2/files/tiles/pbf/aireprotegee/{z}/{x}/{y}.mvt",
        "attributions": "<a href='https://www.quebec.ca/'><br><a href='http://www.droitauteur.gouv.qc.ca/copyright.php'>© Gouvernement du Québec</a><br> <br> Fondé sur<a href='https://github.com/infra-geo-ouverte/igo2'> IGO2</a>",
        "type": "mvt",
        "excludeAttribute": ["layer", "CODE"],
        "featureClass": "feature"
      }
    },
this json generate feature

**Comment by drekss** [comment]
{
      "title": "tenure-elcano-server",
      "declutter": true,
      "visible": false,
      "opacity" : 0.5,
      "styleByAttribute": {
        "type": "regular",
        "attribute": "TYPE",
        "data": [ "Priv"],
        "fill": ["red"],
        "stroke": ["rgba(255,255,0,0)"],
        "width" : [5],
        "label": "TYPE",
        "baseStyle": {
        "stroke": {
          "color": "rgba(255,255,0,0)"
        },
        "fill": {
          "color": "rgba(255,255,0,0)"
        }
      }},
      "sourceOptions": {
        "queryable": true,
        "url": "http://elcano:8080/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=TuilageSmartFaune:Tenures&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/x-protobuf;type=mapbox-vector&TILECOL={x}&TILEROW={y}",
        "pathOffline": "https://io.ion.igo2/_app_file_/storage/emulated/0/Android/data/io.ionic.igo2/files/tiles/pbf/aireprotegee/{z}/{x}/{y}.mvt",
        "attributions": "<a href='https://www.quebec.ca/'><br><a href='http://www.droitauteur.gouv.qc.ca/copyright.php'>© Gouvernement du Québec</a><br> <br> Fondé sur<a href='https://github.com/infra-geo-ouverte/igo2'> IGO2</a>",
        "type": "mvt",
        "excludeAttribute": ["layer", "CODE"],
        "featureClass": "feature"
      }
    },

this json genrate renderFeature. renderFeature are generated by default. featureClass: source options is not necessary

**Comment by drekss** [comment]
{
  "title": "tenure-elcano-server",
  "declutter": true,
  "visible": false,
  "opacity" : 0.5,
  "styleByAttribute": {
    "type": "regular",
    "attribute": "TYPE",
    "data": [ "Priv"],
    "fill": ["red"],
    "stroke": ["rgba(255,255,0,0)"],
    "width" : [5],
    "label": "TYPE",
    "baseStyle": {
    "stroke": {
      "color": "rgba(255,255,0,0)"
    },
    "fill": {
      "color": "rgba(255,255,0,0)"
    }
  }},
  "sourceOptions": {
    "queryable": true,
    "url": "http://elcano:8080/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=TuilageSmartFaune:Tenures&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/x-protobuf;type=mapbox-vector&TILECOL={x}&TILEROW={y}",
    "pathOffline": "https://io.ion.igo2/_app_file_/storage/emulated/0/Android/data/io.ionic.igo2/files/tiles/pbf/aireprotegee/{z}/{x}/{y}.mvt",
    "attributions": "<a href='https://www.quebec.ca/'><br><a href='http://www.droitauteur.gouv.qc.ca/copyright.php'>© Gouvernement du Québec</a><br> <br> Fondé sur<a href='https://github.com/infra-geo-ouverte/igo2'> IGO2</a>",
    "type": "mvt",
    "excludeAttribute": ["layer", "CODE"],
  }
},

this json genrate renderFeature. renderFeature are generated by default. featureClass: source options is not necessary

**Comment by drekss** [comment]
{
      "title": "tenure-elcano-server",
      "declutter": true,
      "visible": false,
      "opacity" : 0.5,
      "styleByAttribute": {
        "type": "regular",
        "attribute": "TYPE",
        "data": [ "Priv"],
        "fill": ["red"],
        "stroke": ["rgba(255,255,0,0)"],
        "width" : [5],
        "label": "TYPE",
        "baseStyle": {
        "stroke": {
          "color": "rgba(255,255,0,0)"
        },
        "fill": {
          "color": "rgba(255,255,0,0)"
        }
      }},
      "sourceOptions": {
        "queryable": true,
        "url": "http://elcano:8080/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=TuilageSmartFaune:Tenures&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/x-protobuf;type=mapbox-vector&TILECOL={x}&TILEROW={y}",
        "pathOffline": "https://io.ion.igo2/_app_file_/storage/emulated/0/Android/data/io.ionic.igo2/files/tiles/pbf/aireprotegee/{z}/{x}/{y}.mvt",
        "attributions": "<a href='https://www.quebec.ca/'><br><a href='http://www.droitauteur.gouv.qc.ca/copyright.php'>© Gouvernement du Québec</a><br> <br> Fondé sur<a href='https://github.com/infra-geo-ouverte/igo2'> IGO2</a>",
        "type": "mvt",
        "excludeAttribute": ["layer", "CODE"],
      }
    },

this json genrate renderFeature. renderFeature are generated by default. featureClass: source options is not necessary

**Comment by gignacnic** [comment]
Related to: https://github.com/infra-geo-ouverte/igo2-lib/issues/514

**Pull request merged**
