### PR TITLE
Control tool at opening

### PR DESCRIPTION
**Pull request by pelord**
**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**
Adding a way to control which tool is open on page initialization. Creating keys and an array of allowed tool names.

Linked with PR infra-geo-ouverte/igo2#236

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications:

**Other information**:

### CODE REVIEW

**Comment by pelord** [comment]
This pr solve issue #218

**Comment by cbourget** [comment]
This is a nice feature but I feel like it be in the app itself instead of the ToolService. I don't think a library component should have control over the router and be the one that decides what the "tool" param does.

**Comment by pelord** [comment]
Yes you are right. 
This has been moved from tool.service to igo2 project (into portal)
Check PR infra-geo-ouverte/igo2#236

**Comment by cbourget** [comment]
Awesome! Thank you

**Pull request merged**
