### PR TITLE
fix(layer.service) fix use of tag sprite with Mapbox style specification

### PR DESCRIPTION
**Pull request by matrottier**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
The use of tag "sprite" (https://docs.mapbox.com/mapbox-gl-js/style-spec/sprite/) do nothing.

**What is the new behavior?**
tag "sprite" working

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:
my cat name is "mitaine".

### CODE REVIEW

**Comment by pelord** [comment]
What is a sprite tag, or a sprite at all?

**Comment by matrottier** [comment]
> What is a sprite tag, or a sprite at all?

sprite tag contains a partial URL ex: assets/x . This URL must link to a json (assets/x.json) AND a png (assets/x.png).  
the png contains all the icons you can use in the style.
the json do the link with the name's icon and it's position in the png.
i did a example in the demo.

**Review by pelord — CHANGES_REQUESTED** [review]
Seem to have some issues within the feature demo!
image
Could you take a look?

**Comment by matrottier** [comment]
i just got a example with relative url.  
the url is relative to the path of the style.  
maplibre does it like that (https://github.com/maplibre/maplibre-gl-js/issues/182)  
i wil do the change.

**Review by pelord — APPROVED** [review]

**Pull request merged**
