### PR TITLE
Catalog force name

### PR DESCRIPTION
**Pull request by PhilippeLafreniere18**
- Allow to add alias to WMS, WMTS or ArcGIS REST catalog's layer (for composite catalog for example)

- regFilters must be used to match the indexes. 

For example, if catalog's config is : 
        {
            "id": "2",
            "url": "https://geoappext.nrcan.gc.ca/arcgis/services/GSCA/basin_f/MapServer/WMSServer?",
            "groupImpose": {"id": "geo", "title": "Géologie"},
            "regFilters": ["^3$", "^6$"],
            "alias": ["Analyse - 1", "Analyse - 2"]
          }
Then it would mean that the layer whose name is 3 going to be rename as "Analyse - 1" and the layer whose name is 6 is going to be rename as "Analyse - 2".

Note that if alias is not mandatory, if none are provided, the service's title is going to be used (like it was before).

Issue https://github.com/infra-geo-ouverte/igo2/issues/515 in igo2 (assemblage)
JIRA : http://jira.msp.gouv.qc.ca:8080/browse/MIGO2-232

### CODE REVIEW

**Comment by pelord** [comment]
Please add the same feature for metadata_url.

**Comment by pelord** [comment]
@PhilippeLafreniere18  Also. Maybe set up an other alternative to match the aliases... In you example, you specify some specific layer.This use case will not work with filtering regex...

**Comment by PhilippeLafreniere18** [comment]
metadata_url for abstract is the next step ! 

And not sure what to you refering to ? I think you have no choice here but to target one layer at the time with regex to rename one layer at the time with the aliases. What do you have in mind ?

**Comment by pelord** [comment]
In fact.. I was thinking to refer to a specific layer name and force some properties..

imposedProperties [
{layerName: 'layerName', properties: { title: 'Title', metadata.url: 'www.perdu.com'}}
]

**Comment by pelord** [comment]
In this case, the forced properties are independent of the regex and you could keep the filtering regex

**Pull request merged**
