### PR TITLE
Favorite context outside api

### PR DESCRIPTION
**Pull request by pelord**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
Non authenticated user could not define favorite contexts.

**What is the new behavior?**
Non authenticated user could now define favorite contexts.
The favorite context is stored (non authenticated user) into the session storage. Based on a config, the app manager could define if the app should allow or not the favorite context.

favoriteContext4NonAuthenticated : true/false

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

### CODE REVIEW

**Comment by pelord** [comment]
image

**Comment by pelord** [comment]
image

**Comment by pelord** [comment]
Some changes are needed. The app path must be provided because the local storage could be shared across multiple apps. Then, it's possible ton set a favorite context inside the app1.. But inside the app2, igo will try to open the favorite context from app1...

**Review by PhilippeLafreniere18 — CHANGES_REQUESTED** [review]
Seems to have a problem with the blue star when the context api is present. The favorite context is well set, but the blue star won't display.

**Review by PhilippeLafreniere18 — APPROVED** [review]

**Pull request merged**
