### PR TITLE
Ogc during next

### PR DESCRIPTION
**Pull request by matrottier**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
ogc filter "During" use "string" as input

**What is the new behavior?**
ogc filter "During" use calendar as input

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

### CODE REVIEW

**Comment by matrottier** [comment]
1- working on this
2- we must add a option, idea for the name ? in this case, we do not display the End Time because it will be start time + step. 
3- maybe in advance mode. You must calculate all the possiblity of the WMS with the step. more complicate.
4- i saw it like the zoom option. it's the max/min of the datasource. 
5- there is 6 examples:  
Inondation (During, optionsFromCapabilities)  
Embâcle (During, Interval from Now, Step: P1D)  
Embâcle (During, Step: P1Y)  
Embâcle (During, Step: P1M)  
Embâcle (During, Step: PT4H)  
Embâcle (During, Step: P2D)

**Comment by matrottier** [comment]
OgcFilterDuringOptions : restrictToStep ?: boolean;   
if true, only one date can be selected and the period is:  selected date + 1x step.

**Comment by pelord** [comment]
> OgcFilterDuringOptions : restrictToStep ?: boolean;
> if true, only one date can be selected and the period is: selected date + 1x step.

And why + 1x step?

**Comment by matrottier** [comment]
> > OgcFilterDuringOptions : restrictToStep ?: boolean;
> > if true, only one date can be selected and the period is: selected date + 1x step.
> 
> And why + 1x step?

to automatically calculate the end time.  
did you want to send only one date ? ex: '2020-08-08 00:00:00'

**Pull request merged**
