### PR TITLE
fix(drawing guide): Fix a regression to the drawing guide that wasn't…

### PR DESCRIPTION
**Pull request by cbourget**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
A regression in the drawing guide in the geometry-input component assumes that we are drawing circles. It doesn't work with any other style.

**What is the new behavior?**
It works with other styles as it should.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

### CODE REVIEW

**Comment by pelord** [comment]
@cbourget  - Your PR is reported to 1.12 release

**Comment by pelord** [comment]
@cbourget How your changes could be tested?

**Comment by pelord** [comment]
I hit this error.

image


@PhilippeLafreniere18  Is it related to your tool? 

image

**Comment by PhilippeLafreniere18** [comment]
I hit the same error when I click in the drawing geometry. It's triggered by the map query event.

**Comment by pelord** [comment]
@cbourget - Your PR is reported to 1.13 or 1.14 release

**Comment by pelord** [comment]
@cbourget Please update the PR and handle conflicts. You could repopen it when you are ready.

**Pull request closed without merging**
